bases:
  - ../../base

namespace: erp-development

resources:
  - ../../base/db

patches:
- target:
    kind: Deployment
    name: mceasy-erp
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        node-label: erp-dev-release
    - op: add
      path: /spec/template/spec/tolerations
      value:
      - key: "erp-dev-release"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
- target:
    kind: StatefulSet
    name: mceasy-erp-db
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        node-label: erp-dev-release
    - op: add
      path: /spec/template/spec/tolerations
      value:
      - key: "erp-dev-release"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"