

from . import account_account
from . import account_bank_statement
from . import account_chart_template
from . import account_fiscal_year
from . import account_journal_dashboard
from . import account_move
from . import account_payment
from . import account_reconcile_model
from . import account_reconcile_model_line
from . import digest
from . import res_config_settings
from . import res_company
from . import bank_rec_widget
from . import bank_rec_widget_line
from . import res_partner
from . import account
from . import account_report
from . import account_analytic_report
from . import account_general_ledger
from . import account_generic_tax_report
from . import account_journal_report
from . import account_cash_flow_report
from . import account_deferred_reports
from . import account_multicurrency_revaluation_report
from . import account_move_line
from . import account_trial_balance_report
from . import account_aged_partner_balance
from . import account_partner_ledger
from . import mail_activity
from . import mail_activity_type
from . import chart_template
from . import account_journal_dashboard
from . import ir_actions
from . import account_sales_report
from . import account_tax
from . import executive_summary_report
from . import account_budget
from . import account_analytic_account
from . import account_asset
from . import account_assets_report
from . import transfer_model
from . import account_followup
from . import account_followup_report
