apiVersion: v1
kind: Service
metadata:
  name: mceasy-erp
spec:
  selector:
    app: mceasy-erp
  ports:
  - name: "http"
    port: 80
    targetPort: 8069
    protocol: TCP
  - name: "longpolling"
    port: 8072
    targetPort: 8072
    protocol: TCP
